import torch.nn as nn

ENABLE_DEV_LOGS = False
DEMO_MODE = True
# DEMO_MODE = False

BATCH_SIZE = 1
BATCHES_TO_AGGREGATE = 22

LEARNING_RATE = 1e-4
EPOCHS = 2
LOSS_FUNCT = nn.MSELoss()

# AGGREGATION_METHOD = "attention"
AGGREGATION_METHOD = "mean"

WEIGHTED_BIN_COUNT = 16 # by using 1 bin, weighted loss would be the same as MSE loss

SAMPLES_TO_USE = 1486
# SAMPLES_TO_USE = 40

STANDART_DEV_TO_KEEP = 1.3
MAX_IMAGES_PER_SAMPLE = 10

USE_SQUARE_METERS = True
USE_ADDITIONAL_METADATA = True