
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./AntdRegistry";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { ConfigProvider } from "antd";
import theme from "./themeConfig";

import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "LOCALHOST 3000",
  description: "Generated by create next app",
};

function RootLayout({ children }: React.PropsWithChildren) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <SessionProvider>
        <ConfigProvider theme={theme}>
          {children}
        </ConfigProvider>
      </SessionProvider>
      </body>
    </html>
  );
}

export default RootLayout;
